export const portoData = [
    {
        id: 1,
        title: "VBM Property System",
        desc: "VBM is a property broker company based in Canggu, Bali. For their growing business, they need more advanced system to track down every newly added property, and all of the legal data through it so it will be more easy to maintain the system",
        img: "https://picsum.photos/seed/picsum/200/300",
        tags: ["WebApp", "Management System", "Mobile App"],
        link: "https://semuarealestate.com/",
        clientName: "Fernando",
        companyName: "VBM Property",
        path: "/vbm-property-system",
    },
    {
        id: 2,
        title: "VBM Portal Website",
        desc: "VBM is a property broker company based in Canggu, Bali. For their growing business, they need more advanced system to track down every newly added property, and all of the legal data through it so it will be more easy to maintain the system",
        img: "https://picsum.photos/seed/picsum/200/300",
        tags: ["WebApp", "Management System", "Mobile App"],
        link: "https://semuarealestate.com/",
        clientName: "Fernando",
        companyName: "VBM Property",
        path: "/vbm-portal-website",
    },
    {
        id: 3,
        title: "Blublub E-Commerce",
        desc: "VBM is a property broker company based in Canggu, Bali. For their growing business, they need more advanced system to track down every newly added property, and all of the legal data through it so it will be more easy to maintain the system",
        img: "https://picsum.photos/seed/picsum/200/300",
        tags: ["WebApp", "Management System", "Mobile App"],
        link: "https://blublub.co/",
        clientName: "Bagas",
        companyName: "Blublub",
        path: "/blublub-e-commerce-system",
    },
];